user_embedding_size: 128
source_item_embedding_size: 128
share_embedding_size: 32
alpha: 0.01
reg_weight: 0.01
gen_weight: 0.1
user_weight_attn: 0.5
enhance_mode: "add"
enhance_weight: 0.5
use_virtual: True
learning_rate: 0.001
train_epochs: ["BOTH:300"]